
#line 3 "archc_lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 88
#define YY_END_OF_BUFFER 89
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[373] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       89,   69,   22,   21,   17,   69,   10,   11,    5,    2,
        6,   69,    1,    1,    4,    3,    8,    7,    9,   68,
       68,   68,   12,   13,   68,   68,   68,   68,   68,   68,
       68,   68,   14,   15,   77,   76,   77,   79,   78,   74,
       73,   72,   81,   88,   80,   83,   22,   17,   83,   82,
       87,   86,   84,   85,   71,   70,   22,   17,   10,   11,
        5,    2,    6,   88,    1,    4,    3,    8,    7,    9,
       68,   68,   68,   68,   68,   14,   15,   48,   47,   47,

        0,   20,    0,   18,   19,    1,   16,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   75,
       70,   68,   68,   68,   68,   48,    0,    0,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,    0,    0,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,    0,   42,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   43,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,

       68,   68,   68,   68,   68,   56,   68,   68,   68,   68,
       68,   68,   68,   68,    0,   68,   24,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   29,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   57,   55,   68,   58,   68,   68,   68,   66,
       68,   68,    0,   46,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   40,   68,   27,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   64,   68,
       68,   68,   68,   67,   68,   23,   25,   68,   68,   36,
       68,   35,   68,   45,   68,   68,   68,   68,   68,   68,

       68,   68,   68,   52,   68,   68,   68,   68,   68,   63,
       68,   68,   68,   68,   68,   34,   37,   28,   68,   68,
       41,   68,   68,   68,   68,   68,   49,   54,   68,   60,
       53,   68,   68,   68,   68,   68,   38,   68,   44,   68,
       68,   32,   68,   68,   68,   59,   68,   68,   68,   65,
       33,   68,   30,   26,   68,   68,   68,   50,   61,   39,
       68,   62,   68,   68,   68,   68,   68,   68,   68,   31,
       51,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    1,    7,
        8,    9,   10,   11,    1,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    1,    1,   21,   22,   23,   22,   22,   22,
       24,   25,   26,   24,   24,   24,   24,   24,   27,   24,
       24,   28,   29,   30,   24,   24,   24,   24,   24,   24,
       31,    1,   32,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   24,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,    1,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[61] =
    {   0,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    1,    1,    1,    1,    1,
        3,    3,    3,    4,    4,    4,    4,    4,    4,    4,
        1,    1,    4,    3,    3,    3,    3,    3,    3,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1
    } ;

static yyconst flex_int16_t yy_base[384] =
    {   0,
        0,    0,   58,   59,  505,  504,   60,   61,   66,   67,
       73,   77,   80,   86,  144,  181,  220,    0,   93,   97,
      506,  509,  509,  509,  509,  463,  509,  509,  509,  509,
       72,   94,   57,   77,  509,  509,  509,  509,  509,  481,
        0,  474,  509,  509,   68,  464,  444,  462,  448,  464,
      446,  458,  509,  509,  509,  509,  482,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  485,  509,
      509,  509,  509,  509,  509,    0,  509,  509,  509,  509,
      509,  509,  481,   96,   96,  509,  509,  509,  509,  509,
      464,    0,  455,  448,  451,  509,  509,    0,  509,    0,

      441,  509,  439,  509,  509,  100,  509,    0,  453,  464,
      451,  432,  441,  445,  435,  446,  429,  439,  424,  509,
        0,  452,  441,  426,  420,    0,  435,  423,   91,  436,
       82,  430,  433,  421,  431,   85,  431,  410,  429,  436,
      245,  423,  426,  413,  420,  428,  426,  431,  402,  404,
      401,  412,  402,  402,  393,  408,  388,  394,  390,  390,
      404,   93,  407,  405,  402,   93,   82,  399,  101,  398,
      383,  389,  385,   55,  394,  378,  509,  407,  408,  398,
      381,  376,  377,  379,  372,  387,  379,  387,  386,  384,
      371,  368,  367,  363,   87,  375,  370,  388,  374,  375,

      356,  357,  372,  371,  358,    0,  354,  362,  367,  354,
      349,  350,  367,  349,  358,  369,    0,  366,  359,  345,
      337,  340,  336,  342,  338,  335,  348,  336,  333,    0,
      348,  334,  333,  342,  341,  329,  345,  333,  337,  336,
      325,  334,    0,    0,  331,  333,  327,  333,  328,    0,
      316,  326,  324,    0,  333,  314,  325,  309,  319,  306,
      317,  304,  319,  304,  315,    0,  308,    0,  303,  303,
      299,  308,  318,  306,  302,  301,  307,  299,    0,  305,
      298,  100,  248,    0,  256,  509,    0,  259,  240,    0,
      240,    0,  239,    0,  241,  239,  244,  236,  176,  175,

      175,  178,  182,    0,  171,  157,  155,  168,  158,    0,
      154,  152,  157,  164,  148,    0,    0,    0,  154,  156,
        0,  141,  144,  139,  151,  152,    0,    0,  145,    0,
        0,  142,  133,  127,  118,  128,    0,  136,    0,  121,
      120,    0,  121,  122,  111,    0,  118,  112,  125,    0,
        0,  112,    0,    0,  115,  122,  124,    0,    0,    0,
      110,    0,  106,  116,  105,  105,  101,   98,   96,    0,
        0,  509,  300,  304,  308,  312,  316,  320,  324,  328,
      330,  131,  334
    } ;

static yyconst flex_int16_t yy_def[384] =
    {   0,
      372,    1,  373,  373,  374,  374,  375,  375,  376,  376,
      377,  377,  378,  378,  379,  379,  372,   17,  380,  380,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  381,
      381,  381,  372,  372,  381,  381,  381,  381,  381,  381,
      381,  381,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  382,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      381,  381,  381,  381,  381,  372,  372,  383,  372,  383,

      372,  372,  372,  372,  372,  372,  372,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  372,
      382,  381,  381,  381,  381,  383,  372,  372,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  372,  372,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  372,  372,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  372,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  372,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  372,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,    0,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372
    } ;

static yyconst flex_int16_t yy_nxt[570] =
    {   0,
       22,   23,   24,   23,   25,   26,   27,   28,   22,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   41,   41,   41,   42,   41,   41,   41,   41,
       43,   44,   22,   45,   46,   47,   48,   41,   41,   41,
       41,   49,   41,   41,   41,   50,   41,   41,   51,   41,
       52,   41,   41,   41,   41,   41,   41,   41,   53,   54,
       56,   56,   61,   61,   62,   62,   57,   57,   64,   64,
      106,  106,   65,   65,   67,   24,   67,   68,   67,   24,
       67,   68,   72,  102,  212,   69,   73,   74,   72,   69,
      106,  106,   73,   74,   99,   64,  100,  100,   99,   64,

      100,  100,  104,  111,  104,  213,  105,  103,  105,  106,
      106,  146,  107,  106,  106,  149,  147,  203,  112,  158,
      150,  151,  152,  153,   65,   65,  194,  159,  195,  196,
      201,   70,  204,  121,  233,   70,  206,  197,   73,   74,
      202,  311,  207,  234,   73,   74,   64,  371,  312,  370,
      369,  368,  367,  366,  365,  364,  363,   76,   76,  362,
      361,  360,  359,  358,   76,   76,   76,  357,  356,  355,
      354,  353,  352,  351,  350,  349,  348,   76,   76,   76,
       76,   76,   76,   64,  347,  346,  345,  344,  343,  342,
      341,  340,  339,  338,   76,   76,  337,  336,  335,  334,

      333,   76,   76,   76,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  323,   76,   76,   76,   76,   76,   76,
       64,   77,   24,   77,   78,   64,   79,   80,   64,   81,
       82,   83,   84,   85,   85,   86,   87,   88,   89,   90,
       91,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       64,   64,   64,   93,   94,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       95,   92,   92,   92,   92,   92,   92,   92,   96,   97,
      164,  165,  322,  166,  321,  320,  167,  319,  318,  317,
      168,  316,  315,  169,  170,  171,  172,  314,  313,  173,

       55,   55,   55,   55,   58,   58,   58,   58,   60,   60,
       60,   60,   63,   63,   63,   63,   66,   66,   66,   66,
       71,   71,   71,   71,   75,   75,   75,   75,   98,   98,
       98,   98,  108,  108,  126,  310,  126,  126,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  248,

      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  235,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  211,  210,  209,  208,  205,  200,  199,  198,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      163,  162,  161,  160,  157,  156,  155,  154,  148,  145,
      144,  143,  142,  141,  140,  139,  138,  137,  136,  135,
      134,  133,  132,  131,  130,  129,  128,  127,  125,  124,
      123,  122,  102,  104,  120,  119,  118,  117,  116,  115,

      114,  113,  110,  109,  101,  372,   59,   59,   21,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372
    } ;

static yyconst flex_int16_t yy_chk[570] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    7,    8,    7,    8,    3,    4,    9,   10,
       33,   33,    9,   10,   11,   11,   11,   11,   12,   12,
       12,   12,   13,   31,  174,   11,   13,   13,   14,   12,
       34,   34,   14,   14,   19,   19,   19,   19,   20,   20,

       20,   20,   32,   45,   84,  174,   32,   31,   84,   85,
       85,  129,   33,  106,  106,  131,  129,  167,   45,  136,
      131,  131,  131,  131,    9,   10,  162,  136,  162,  162,
      166,   11,  167,  382,  195,   12,  169,  162,   13,   13,
      166,  282,  169,  195,   14,   14,   15,  369,  282,  368,
      367,  366,  365,  364,  363,  361,  357,   15,   15,  356,
      355,  352,  349,  348,   15,   15,   15,  347,  345,  344,
      343,  341,  340,  338,  336,  335,  334,   15,   15,   15,
       15,   15,   15,   16,  333,  332,  329,  326,  325,  324,
      323,  322,  320,  319,   16,   16,  315,  314,  313,  312,

      311,   16,   16,   16,  309,  308,  307,  306,  305,  303,
      302,  301,  300,  299,   16,   16,   16,   16,   16,   16,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
      141,  141,  298,  141,  297,  296,  141,  295,  293,  291,
      141,  289,  288,  141,  141,  141,  141,  285,  283,  141,

      373,  373,  373,  373,  374,  374,  374,  374,  375,  375,
      375,  375,  376,  376,  376,  376,  377,  377,  377,  377,
      378,  378,  378,  378,  379,  379,  379,  379,  380,  380,
      380,  380,  381,  381,  383,  281,  383,  383,  280,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  267,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      255,  253,  252,  251,  249,  248,  247,  246,  245,  242,
      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  229,  228,  227,  226,  225,  224,  223,  222,  221,
      220,  219,  218,  216,  215,  214,  213,  212,  211,  210,

      209,  208,  207,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  194,  193,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      176,  175,  173,  172,  171,  170,  168,  165,  164,  163,
      161,  160,  159,  158,  157,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  147,  146,  145,  144,  143,  142,
      140,  139,  138,  137,  135,  134,  133,  132,  130,  128,
      127,  125,  124,  123,  122,  119,  118,  117,  116,  115,
      114,  113,  112,  111,  110,  109,  103,  101,   95,   94,
       93,   91,   83,   69,   57,   52,   51,   50,   49,   48,

       47,   46,   42,   40,   26,   21,    6,    5,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "archc_lex.l"
/*  ArchC Language Sintax for GNU Flex
    Copyright (C) 2002-2004  The ArchC Team
    Please see license file distributed with this file.
    
    Visit http://www.archc.org for more information.
*/
#line 9 "archc_lex.l"
#include <stdlib.h>
#include <string.h>
#include "archc_grammar.h" /* generated by yyac */

#define MAX_STR_CONST  256
#define MAX_CODE_CONST  256
#define MAX_BLOCK_CONST  4096
#define DEBUG_LEX 0
#define MAX_INCLUDE_DEPTH 10

YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
int include_stack_ptr = 0;








#line 729 "archc_lex.c"

#define INITIAL 0
#define COMMENT 1
#define COMMENT1 2
#define STRING 3
#define BLOCK_START 4
#define BLOCK_ALT_START 5
#define BLOCK_STATE 6
#define HEXA 7
#define ARCH 8
#define INCLUDE 9

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 38 "archc_lex.l"


 char string_buf[MAX_STR_CONST];
 char* string_buf_ptr;
 char block_buf[MAX_BLOCK_CONST];
 char* block_buf_ptr;
 int brace_level = 0;
 int paren_level = 0;
 int return_state;
 extern unsigned line_num;

 /***************************************************/
 /* Regular expressions for general tokens in ArchC */
 /***************************************************/

#line 936 "archc_lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 373 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 509 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 53 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("An integer: %s (%d)\n", yytext, atoi(yytext));
  #endif
  yylval.value = atoi(yytext);
  return INT;
 }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 61 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("COMMA: %s\n", yytext);
  #endif
  return COMMA;
 }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 68 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("SEMICOLON: %s\n", yytext);
  #endif
  return SEMICOLON;
 }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 75 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("COLON: %s\n", yytext);
  #endif
  return COLON;
 }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 82 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("PLUS: %s\n", yytext);
  #endif
  return PLUS;
 }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 89 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("DOT: %s\n", yytext);
  #endif
  return DOT;
 }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 96 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("EQUAL: %s\n", yytext);
  #endif
  return EQ;
 }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 103 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("LT: %s\n", yytext);
  #endif
  return LT;
 }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 110 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("GT: %s\n", yytext);
  #endif
  return GT;
 }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 117 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("LPAREN: %s\n", yytext);
  #endif
  return LPAREN;
 }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 124 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("RPAREN: %s\n", yytext);
  #endif
  return RPAREN;
 }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 131 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("LBRACK: %s\n", yytext);
  #endif
  return LBRACK;
 }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 138 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("RBRACK: %s\n", yytext);
  #endif
  return RBRACK;
 }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 145 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("LBRACE: %s\n", yytext);
  #endif
  return LBRACE;
 }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 152 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("RBRACE: %s\n", yytext);
  #endif
  return RBRACE;
 }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 159 "archc_lex.l"
BEGIN(HEXA);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 161 "archc_lex.l"
{
  string_buf_ptr = string_buf;
  return_state = YY_START;
  BEGIN(STRING);
 }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 167 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("Entering comment: \n");
  #endif
  return_state = YY_START;
  BEGIN(COMMENT);
 }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 175 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("Entering comment1: \n");
  #endif
  return_state = YY_START;
  BEGIN(COMMENT1);
 }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 183 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("PP \n");
  #endif
  return PP;
 }
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 190 "archc_lex.l"
{
  line_num++;
  #if DEBUG_LEX
  printf("New line: %d\n", line_num);
  #endif
 }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 197 "archc_lex.l"
/* eat up spaces */ {
  #if DEBUG_LEX
  printf("Eating space: <%s>\n", yytext);
  #endif
 }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 203 "archc_lex.l"
BEGIN(INCLUDE);
	YY_BREAK
/***************************************************/
/* Regular expressions for ArchC ISA reserved words*/
/***************************************************/
case 24:
YY_RULE_SETUP
#line 209 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_ISA: %s\n", yytext);
  #endif
  return AC_ISA_UPPER;
 }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 216 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("ISA_CTOR: %s\n", yytext);
  #endif
  return ISA_CTOR;
 }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 223 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("SET_DECODER: %s\n", yytext);
  #endif
  return SET_DECODER;
 }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 230 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("SET_ASM: %s\n", yytext);
  #endif
  return SET_ASM;
 }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 237 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_ASM_ASSEMBLER: %s\n", yytext);
  #endif
  return AC_ASM_ASSEMBLER;
 }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 244 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("MAP_TO: %s\n", yytext);
  #endif
  return MAP_TO;
 }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 251 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_ASM_COMMENT: %s\n", yytext);
  #endif
  return AC_ASM_COMMENT;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 258 "archc_lex.l"
{
#if DEBUG_LEX
  printf("AC_ASM_LINE_COMMENT: %s\n", yytext);
#endif
  return AC_ASM_LINE_COMMENT;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 265 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("SET_CYCLES: %s\n", yytext);
  #endif
  return SET_CYCLES;
 }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 272 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("CYCLE_RANGE: %s\n", yytext);
  #endif
  return CYCLE_RANGE;
 }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 279 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_FORMAT: %s\n", yytext);
  #endif
  return AC_FORMAT;
 }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 286 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_INSTR: %s\n", yytext);
  #endif
  return AC_INSTR;
 }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 293 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_GROUP: %s\n", yytext);
  #endif
  return AC_GROUP;
 }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 300 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_HELPER: %s\n", yytext);
  #endif
  return_state = YY_START;
  BEGIN(BLOCK_ALT_START);
  return AC_HELPER;
 }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 309 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_ASM_MAP: %s\n", yytext);
  #endif
  return AC_ASM_MAP;
 }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 317 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("PSEUDO_INSTR: %s\n", yytext);
  #endif
  return PSEUDO_INSTR;
 }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 324 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("IS_JUMP: %s\n", yytext);
  #endif
  return_state = YY_START;
  BEGIN(BLOCK_START);
  return IS_JUMP;
 }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 333 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("IS_BRANCH: %s\n", yytext);
  #endif
  return_state = YY_START;
  BEGIN(BLOCK_START);
  return IS_BRANCH;
 }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 342 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("COND: %s\n", yytext);
  #endif
  return_state = YY_START;
  BEGIN(BLOCK_START);
  return COND;
 }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 351 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("DELAY: %s\n", yytext);
  #endif
  return_state = YY_START;
  BEGIN(BLOCK_START);
  return DELAY;
 }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 360 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("DELAY_COND: %s\n", yytext);
  #endif
  return_state = YY_START;
  BEGIN(BLOCK_START);
  return DELAY_COND;
 }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 369 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("BEHAVIOR: %s\n", yytext);
  #endif
  return_state = YY_START;
  BEGIN(BLOCK_START);
  return BEHAVIOR;
 }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 378 "archc_lex.l"
{
  /* Changing to ARCH state */
  #if DEBUG_LEX
  printf("AC_ARCH: %s\n", yytext);
  #endif
  line_num = 1;
  BEGIN(ARCH);
  return AC_ARCH;
 }
	YY_BREAK
/**************************************************/
/* Regular expressions for including other files  */
/**************************************************/
case 47:
YY_RULE_SETUP
#line 392 "archc_lex.l"
{}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 394 "archc_lex.l"
{
  int i, j;

  if (include_stack_ptr >= MAX_INCLUDE_DEPTH)
  {
   fprintf(stderr, "Too many #include's");
   exit(1);
  }
  include_stack[include_stack_ptr++] = YY_CURRENT_BUFFER;
  if (yytext[yyleng - 1] == '\"')
   yytext[yyleng - 1] = '\0';
  if (yytext[0] == '\"')
   yytext++;
  yyin = fopen(yytext, "r");
  if (!yyin)
  {
   fprintf(stderr, "ArchC Lexical ERROR: Couldn't open input file %s \n", yytext);
  }
  yy_switch_to_buffer(yy_create_buffer(yyin,YY_BUF_SIZE));
  BEGIN(INITIAL);
 }
	YY_BREAK
/******************************************************/
/* Regular expressions for ARchC ARCH reserved words */
/******************************************************/
case 49:
YY_RULE_SETUP
#line 420 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("ARCH_CTOR: %s\n", yytext);
  #endif
  return ARCH_CTOR;
 }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 427 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_TLM_PORT: %s\n", yytext);
  #endif
  return AC_TLM_PORT;
 }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 434 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_TLM_INTR_PORT: %s\n", yytext);
  #endif
  return AC_TLM_INTR_PORT;
 }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 441 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_CACHE: %s\n", yytext);
  #endif
  return AC_CACHE;
 }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 448 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_ICACHE: %s\n", yytext);
  #endif
  return AC_ICACHE;
 }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 455 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_DCACHE: %s\n", yytext);
  #endif
  return AC_DCACHE;
 }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 462 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_MEM: %s\n", yytext);
  #endif
  return AC_MEM;
 }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 469 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_PC: %s\n", yytext);
  #endif
  return AC_PC;
 }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 476 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("ac_isa: %s\n", yytext);
  #endif
  return AC_ISA;
 }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 483 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_REG: %s\n", yytext);
  #endif
  return AC_REG;
 }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 490 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_REGBANK: %s\n", yytext);
  #endif
  return AC_REGBANK;
 }
	YY_BREAK
/*** Experimental feature. --Marilia
<ARCH>"ac_buffer" {
  #if DEBUG_LEX
  printf("AC_BUFFER: %s\n", yytext);
  #endif
  return AC_BUFFER;
 }
 */
case 60:
YY_RULE_SETUP
#line 506 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_FORMAT FOR ARCH: %s\n", yytext);
  #endif
  return AC_FORMAT;
 }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 513 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_WORDSIZE: %s\n", yytext);
  #endif
  return AC_WORDSIZE;
 }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 520 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_FETCHSIZE: %s\n", yytext);
  #endif
  return AC_FETCHSIZE;
 }
	YY_BREAK
/*** Experimental feature. --Marilia
<ARCH>"ac_fetchbuffersize" {
  #if DEBUG_LEX
  printf("AC_FETCHBUFFERSIZE: %s\n", yytext);
  #endif
  return AC_FETCHBUFFERSIZE;
 }
 */
case 63:
YY_RULE_SETUP
#line 536 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_STAGE: %s\n", yytext);
  #endif
  return AC_STAGE;
 }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 543 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("AC_PIPE: %s\n", yytext);
  #endif
  return AC_PIPE;
 }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 550 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("SET_ENDIAN: %s\n", yytext);
  #endif
  return SET_ENDIAN;
 }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 557 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("BIND_TO: %s\n", yytext);
  #endif
  return BIND_TO;
 }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 564 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("BIND_TO: %s\n", yytext);
  #endif
  return BIND_TO;
 }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 571 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("An identifier: %s\n", yytext);
  #endif
  yylval.text = (char*) malloc(sizeof(char) * (strlen(yytext) + 1));
  strcpy(yylval.text, yytext);
  return ID;
 }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ARCH):
#line 580 "archc_lex.l"
{
  if (--include_stack_ptr < 0)
  {
   BEGIN(INITIAL);
   yyterminate();
  }
  else
  {
   yy_delete_buffer(YY_CURRENT_BUFFER);
   yy_switch_to_buffer(include_stack[include_stack_ptr]);
  }
 }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 593 "archc_lex.l"
{
  printf("ArchC Unmatched input at line %d: <%s>\n", line_num, yytext);
 }
	YY_BREAK
/********************************************************/
/* Regular expressions for hexadecimal numbers in ArchC */
/********************************************************/
case 70:
YY_RULE_SETUP
#line 601 "archc_lex.l"
{ /* Handling Hexadecimal numbers */
  #if DEBUG_LEX
  printf("An hexa integer: 0x%s (%d)\n", yytext, (int) strtol(yytext, NULL, 16));
  #endif
  yylval.value = (int) strtol(yytext, NULL, 16);
  BEGIN(INITIAL);
  return INT;
 }
	YY_BREAK
case YY_STATE_EOF(HEXA):
#line 610 "archc_lex.l"
{
  fprintf(stderr, "ArchC Lexical ERROR: Unexpected end of file\n");
  yyterminate();
 }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 615 "archc_lex.l"
{
  fprintf(stderr, "ArchC Lexical ERROR: Unrecognized character in hexa state: %s\n", yytext);
  BEGIN(INITIAL);
  yyterminate();
 }
	YY_BREAK
/*****************************************************/
/* Regular expressions for handling Strings in ArchC */
/*****************************************************/
case 72:
YY_RULE_SETUP
#line 625 "archc_lex.l"
{ /* Handling Strings*/
  /* saw closing quote - all done */
  *string_buf_ptr = '\0';
  /* return string constant token type and
   * value to parser
   */
  #if DEBUG_LEX
  printf("A string: %s\n", string_buf);
  printf("Returning token: %d\n", STR);
  #endif
  yylval.text = (char*) malloc(sizeof(char) * (strlen(string_buf) + 1));
  strcpy(yylval.text, string_buf);
  BEGIN(return_state);
  return STR;
 }
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 641 "archc_lex.l"
{
  /* error - unterminated string constant */
  /* generate error message */
  *string_buf_ptr = '\0';
  printf("AC_ERROR: Line %d: Unterminated string constant: %s\n", line_num, string_buf);
  yyterminate();
 }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 649 "archc_lex.l"
{
  *string_buf_ptr++ = *yytext;
 }
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 653 "archc_lex.l"
{
  fprintf(stderr, "ArchC Lexical ERROR: Unexpected end of file\n");
  yyterminate();
 }
	YY_BREAK
/*****************************************************/
/* Regular expressions for comments in ArchC */
/*****************************************************/
case 75:
YY_RULE_SETUP
#line 662 "archc_lex.l"
{
  #if DEBUG_LEX
  printf("End of comment in line: %d\n", line_num);
  #endif
  BEGIN(return_state);
 }
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 669 "archc_lex.l"
{
  line_num++;
  #if DEBUG_LEX
  printf("Comment. New line: %d\n", line_num);
  #endif
 }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 676 "archc_lex.l"
{}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 678 "archc_lex.l"
{
  BEGIN(INITIAL);
  fprintf(stderr, "ArchC Lexical ERROR: Unexpected end of file\n");
  yyterminate();
 }
	YY_BREAK
/* Comment style regular expressions*/
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 685 "archc_lex.l"
{
  line_num++;
  #if DEBUG_LEX
  printf("Leaving comment1. New line: %d\n", line_num);
  #endif
  BEGIN(return_state);
 }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 693 "archc_lex.l"
{}
	YY_BREAK
case YY_STATE_EOF(COMMENT1):
#line 695 "archc_lex.l"
{
  BEGIN(INITIAL);
  fprintf(stderr, "ArchC Lexical ERROR: Unexpected end of file\n");
  yyterminate();
 }
	YY_BREAK
/*****************************************************/
/* Regular expressions for blocks in ArchC */
/*****************************************************/
case 80:
YY_RULE_SETUP
#line 705 "archc_lex.l"
{
  if (*yytext == '{')
   brace_level++;
  if (*yytext == '(')
   paren_level++;
  block_buf_ptr = block_buf;
  BEGIN(BLOCK_STATE);
 }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 714 "archc_lex.l"
{
  printf("ArchC Lexical ERROR: Block must begin at line %d\n", line_num);
  yyterminate();
 }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 719 "archc_lex.l"
{
  brace_level++;
  block_buf_ptr = block_buf;
  BEGIN(BLOCK_STATE);
 }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 725 "archc_lex.l"
{
  printf("ArchC Unmatched input at line %d: <%s>\n", line_num, yytext);
 }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 729 "archc_lex.l"
{
  if (*yytext == '{')
   brace_level++;
  if (*yytext == '(')
   paren_level++;
  *block_buf_ptr++ = *yytext;
 }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 737 "archc_lex.l"
{
  if (*yytext == '}')
   brace_level--;
  if (*yytext == ')')
   paren_level--;
  if (!((brace_level == 0) && (paren_level == 0)))
   *block_buf_ptr++ = *yytext;
  else
  {
   /* end block state */
   *block_buf_ptr = '\0';
   yylval.text = (char*) malloc(sizeof(char) * (strlen(block_buf) + 1));
   strcpy(yylval.text,block_buf);
   BEGIN(INITIAL);
   return BLOCK;
  }
 }
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 755 "archc_lex.l"
{
  line_num++;
  *block_buf_ptr++ = *yytext;
 }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 760 "archc_lex.l"
{
  *block_buf_ptr++ = *yytext;
 }
	YY_BREAK
case YY_STATE_EOF(BLOCK_STATE):
#line 764 "archc_lex.l"
{
  BEGIN(INITIAL);
  fprintf(stderr, "ArchC Lexical ERROR: Unexpected end of file inside a block\n");
  yyterminate();
 }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 770 "archc_lex.l"
ECHO;
	YY_BREAK
#line 2010 "archc_lex.c"
case YY_STATE_EOF(BLOCK_START):
case YY_STATE_EOF(BLOCK_ALT_START):
case YY_STATE_EOF(INCLUDE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 373 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 373 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 372);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 770 "archc_lex.l"



